version: "3.8"

services:
  remove-bg:
    build: .
    ports:
      - "5000:5000"
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
    # Uncomment jika ingin limit memory
    # deploy:
    #   resources:
    #     limits:
    #       memory: 512M
